### ISSUE TITLE
Mirror Not longer support?

### ISSUE THREAD

**Issue by yamatoyakko** [czvtools/cygwinxp#1]
ftp://www.fruitbat.org/pub/cygwin/  longer support?

**Comment by czvtools** [comment]
Hello, I don't understand the question. The links from ftp://www.fruitbat.org/pub/cygwin/... work for me, I tested it now. Please write in more details what you experienced as a problem.

**Comment by yamatoyakko** [comment]
At first,I think it just set the mirror address at ftp://www.fruitbat.org/pub/cygwin/circa/2016/08/30/104223/x86/ and setup-x86-2.874.exe will be work fine,now I realize that: use your scripts to down the pkg binary at first,and install from local folder，thx very much~
